main_app/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('recipes/', views.recipes_index, name='index'),
    path('recipes/<int:recipe_id>/', views.recipes_detail, name='detail'),
    path('recipes/create/', views.RecipeCreate.as_view(), name='recipes_create'),
    path('recipes/<int:pk>/update/', views.RecipeUpdate.as_view(), name='recipes_update'),
    path('recipes/<int:pk>/delete/', views.RecipeDelete.as_view(), name='recipes_delete'),
    path('recipes/<int:recipe_id>/add_recipelog/', views.add_recipelog, name='add_recipelog'),
    path('recipes/<int:recipe_id>/assoc_ingredient/<int:ingredient_id>/', views.assoc_ingredient, name='assoc_ingredient'),
    path('recipes/<int:recipe_id>/unassoc_ingredients/<int:ingredient_id>/', views.unassoc_ingredient, name='unassoc_ingredient'),
    path('ingredients/', views.IngredientList.as_view(), name='ingredients_index'),
    path('ingredients/<int:pk>/', views.IngredientDetail.as_view(), name='ingredients_detail'),
    path('ingredients/create/', views.IngredientCreate.as_view(), name='ingredients_create'),
    path('ingredients/<int:pk>/update/', views.IngredientUpdate.as_view(), name='ingredients_update'),
    path('ingredients/<int:pk>/delete/', views.IngredientDelete.as_view(), name='ingredients_delete'),
    path('accounts/signup/', views.signup, name='signup'),
    path('recipes/<int:recipe_id>/add_photo/', views.add_photo, name='add_photo'),
    ]

reciperotator/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/models.py
from django.db import models
from django import forms
from django.urls import reverse
from django.contrib.auth.models import User


CUISINES = (('NA', 'North American'), ('SA','South American'), ('LA', 'Latin American'), ('AS', 'Asian'), ('EU', 'European'), ('MD', 'Mediterranean'), ('AF', 'African'))
# Create your models here.

RATINGS = (('One Star', '★'),('Two Star', '★★'),('Three Star', '★★★'),('Four Star', '★★★★'),('Five Star', '★★★★★'))
class Ingredient(models.Model):
    ingred_name = models.CharField(max_length=50)
    amount = models.CharField(max_length=50)
    measurement = models.CharField(max_length=20, default="oz")

    def __str__(self):
        return self.ingred_name

    def get_absolute_url(self):
        return reverse('ingredients_detail', kwargs={'pk': self.id})    
class Recipe(models.Model): 
    name = models.CharField(max_length=100)
    cuisine = models.CharField(
        max_length=3,
        choices=CUISINES,
        default=CUISINES[0][0]
    )
    instructions = models.TextField(max_length=500)
    servingsize = models.IntegerField()
    calories = models.IntegerField()
    author = models.CharField(max_length=100)
    ingredients = models.ManyToManyField(Ingredient)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self): 
        return self.name

    def get_absolute_url(self):
        return reverse('detail', kwargs={"recipe_id": self.id})

class RecipeLog(models.Model):
    recipe_use = models.BooleanField(default=True)
    date = models.DateField('Log Date')
    review_name = models.CharField(max_length=50)
    review = models.TextField(max_length=500)
    rating = models.CharField(
        max_length=20,
        choices = RATINGS,
        default = RATINGS[0][0]
    )
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_rating_display()} on {self.date}"
    
    class Meta:
        ordering = ['-date']

class Photo(models.Model):
    url = models.CharField(max_length=200)
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)

    def __str__(self): 
        return f"Photo for recipe_id: {self.recipe_id} @{self.url}"

    

main_app/forms.py
from django.forms import ModelForm
from .models import RecipeLog

class RecipeLogForm(ModelForm):
  class Meta:
    model = RecipeLog
    fields = ['date', 'review_name', 'recipe_use', 'review', 'rating']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
import uuid
import boto3
from .models import Recipe, Ingredient, Photo
from .forms import RecipeLogForm

S3_BASE_URL = 'https://s3.us-west-1.amazonaws.com/'
BUCKET = 'recipe-rotator'

# Create your views here.

class RecipeCreate(LoginRequiredMixin, CreateView):
    model = Recipe
    fields = '__all__'
    # fields = ['name', 'cuisine', 'instructions', 'servingsize', 'calories', 'author', 'ingredients']
    # success_url = '/recipes/'
    def form_valid(self, form):
      form.instance.user = self.request.user  
      return super().form_valid(form)

class RecipeUpdate(LoginRequiredMixin, UpdateView):
  model = Recipe
  fields = '__all__'

class RecipeDelete(LoginRequiredMixin, DeleteView):
  model = Recipe
  success_url = '/recipes/'



def home(request): 
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

@login_required
def recipes_index(request):
    recipes = Recipe.objects.filter(user=request.user)
    return render(request, 'recipes/index.html', { 'recipes': recipes })

@login_required
def recipes_detail(request, recipe_id): 
    recipe = Recipe.objects.get(id=recipe_id)
    ingredients_recipe_doesnt_have = Ingredient.objects.exclude(id__in = recipe.ingredients.all().values_list('id'))
    recipelog_form = RecipeLogForm()
    return render(request, 'recipes/detail.html', {
         'recipe': recipe ,
         'recipelog_form': recipelog_form,
         'ingredients': ingredients_recipe_doesnt_have 
         })

@login_required
def add_recipelog(request, recipe_id):
  form = RecipeLogForm(request.POST)
  if form.is_valid():
    new_recipelog = form.save(commit=False)
    new_recipelog.recipe_id = recipe_id
    new_recipelog.save()
  return redirect('detail', recipe_id=recipe_id)

@login_required
def assoc_ingredient(request, recipe_id, ingredient_id):
  Recipe.objects.get(id=recipe_id).ingredients.add(ingredient_id)
  return redirect('detail', recipe_id=recipe_id)

@login_required 
def unassoc_ingredient(request, recipe_id, ingredient_id):
    Recipe.objects.get(id=recipe_id).ingredients.remove(ingredient_id)
    return redirect('detail', recipe_id=recipe_id)

@login_required
def add_photo(request, recipe_id): 
  photo_file = request.FILES.get('photo-file', None)
  if photo_file:
    s3 = boto3.client('s3')
    key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
    try:
      s3.upload_fileobj(photo_file, BUCKET, key)
      url = f"{S3_BASE_URL}{BUCKET}/{key}"
      Photo.objects.create(url=url, recipe_id=recipe_id)
    except: 
      print('An error occurred uploading file to S3')
  return redirect('detail', recipe_id=recipe_id)

def signup(request):
  error_message = ''
  if request.method == 'POST':
    form = UserCreationForm(request.POST)
    if form.is_valid():
      user = form.save()
      login(request, user)
      return redirect('index')
    else:
      error_message = 'Invalid sign up - try again'
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)

class IngredientList(LoginRequiredMixin, ListView):
    model = Ingredient


class IngredientDetail(LoginRequiredMixin, DetailView):
    model = Ingredient


class IngredientCreate(LoginRequiredMixin, CreateView):
    model = Ingredient
    fields = '__all__'


class IngredientUpdate(LoginRequiredMixin, UpdateView):
    model = Ingredient
    fields = '__all__'


class IngredientDelete(LoginRequiredMixin, DeleteView):
    model = Ingredient
    success_url = '/ingredients/'

main_app/templates/about.html
{% extends 'base.html' %} 

{% block content %} 

    <h1>About Recipe Rotator</h1>
    <hr />
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatum unde officiis quasi, et veniam optio maxime iusto impedit quo distinctio eveniet, rerum ipsam culpa voluptas mollitia eligendi nobis esse. Pariatur.</p>

{% endblock %} 

main_app/templates/base.html
{% load static %} 

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Recipe Rotator</title>
  {% comment %} <link rel="stylesheet" href="https://cdn.metroui.org.ua/v4.3.2/css/metro-all.min.css"> {% endcomment %}
  <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
   <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
  />
  <link
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
    rel="stylesheet"
  />
  <link
    href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
    rel="stylesheet"
  />
  <link href="https://fonts.googleapis.com/css2?family=Bad+Script&family=Courgette&family=Elsie:wght@900&family=Julius+Sans+One&family=Kaushan+Script&family=Trocchi&display=swap" rel="stylesheet">
  <link 
  href="https://fonts.googleapis.com/icon?family=Material+Icons"
    rel="stylesheet"/>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.3.0/mdb.min.css" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
 <script src="https://cdn.metroui.org.ua/v4.3.2/js/metro.min.js"></script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav class="navbar navbar-expand-lg navbar-light bg-dark">
      <div class="container-fluid">
       <h2 class="navbar-brand">
       Recipe <span class="material-icons nav-icon">menu_book</span><strong>Rotator</strong></h2>
      <button
        class="navbar-toggler"
        type="button"
        data-mdb-toggle="collapse"
        data-mdb-target="#navbarText"
        aria-controls="navbarText"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'about' %}">Learn More</a>
          </li>
          {% if user.is_authenticated %} 
          <li class="nav-item">
            <a class="nav-link" href="{% url 'recipes_create' %}">Add Recipe</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'ingredients_create' %}">Add Ingredients</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'ingredients_index' %}">All Ingredients</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'index' %}">All Recipes</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
          </li>
          {% else %} 
          <li class="nav-item">
            <a class="nav-link" href="{% url 'signup' %}">Sign Up</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">Log In</a>
          </li>
          {% endif %} 
        </ul>
        <span class="navbar-text">
          Logged in as {{recipe.user}}
        </span>
      </div>
    </div>
  </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2021 Recipe Rotator &nbsp;</div>
  </footer>
  <script
  type="text/javascript"
  src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.3.0/mdb.min.js"
></script>
</body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>Home</h1>

{% endblock %}

main_app/templates/main_app/ingredient_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Ingredient</h1>

  <h4>Are you sure you want to delete <span>{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'ingredients_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/ingredient_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Ingredient Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ ingredient.amount}} {{ ingredient.measurement }} of </span>
        <span class="card-title">{{ ingredient.ingred_name }}</span>
      </div>
      <div class="card-action">
        <a href="{% url 'ingredients_update' ingredient.id %}">Edit</a>
        <a href="{% url 'ingredients_delete' ingredient.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/ingredient_form.html
{% extends 'base.html' %}
{% block content %}
  {% if object %}
    <h1>Edit <span>{{object.name}}</span></h1>
  {% else %}
    <h1>Add Ingredient</h1>
  {% endif %}
  
  <form action="" method="post">
     <table>
     {% csrf_token %}
       {{ form.as_table}}
      <input type="submit" class="btn btn-primary" value="Submit">
    </table>
 </form>
{% endblock %}

main_app/templates/main_app/ingredient_list.html
{% extends 'base.html' %}
{% block content %}

<h1 class="add-title">Recently Ingredients</h1>

{% for ingredient in ingredient_list %}
  <a href="{% url 'ingredients_detail' ingredient.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ ingredient.ingred_name }}</span>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}

main_app/templates/main_app/recipe_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Recipe</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' recipe.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/recipes/detail.html
{% extends 'base.html' %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
{% block content %}

<h1 class="edit-title">Let's Cook
  <strong class="detail-strong">{{ recipe.name}}</strong></h1>
  {% for photo in recipe.photo %} 
  <img class="detail-img" src="{{ photo.url }}" class="card-img-top">
{% empty %} 
   <img
        src="https://i.imgur.com/nh2P46i.jpg"
        class="card-img-top detail-img"
        alt="..."
    /> 
  {% endfor %} 
<div class="container-details">
  <div class="accordion" style="margin-right: 65px; margin-left: 120px; width: 40rem" id="accordionExample">
  <div class="accordion-item">
  <h2 class="accordion-header custom-accord" id="headingOne">
     <button
        class="accordion-button accord-btn collapse-text"
        type="button"
        data-mdb-toggle="collapse"
        data-mdb-target="#collapseOne"
        aria-expanded="true"
        aria-controls="collapseOne"
      >Follow the recipe step by step
      </button>
      </h2>
      <div
      id="collapseOne"
      class="accordion-collapse collapse show"
      aria-labelledby="headingOne"
      data-mdb-parent="#accordionExample"
    >
    <div class="accordion-body">
        {{recipe.instructions}}
    </div>
  </div>
</div>
<div class="accordion-item">
    <h2 class="accordion-header custom-accord" id="headingTwo">
      <button
        class="accordion-button collapsed collapse-text"
        type="button"
        data-mdb-toggle="collapse"
        data-mdb-target="#collapseTwo"
        aria-expanded="false"
        aria-controls="collapseTwo"
      >
        Cuisine Classification
      </button>
    </h2>
    <div
      id="collapseTwo"
      class="accordion-collapse collapse"
      aria-labelledby="headingTwo"
      data-mdb-parent="#accordionExample"
    >
      <div class="accordion-body">
        {{recipe.cuisine}}
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header custom-accord" id="headingThree">
      <button
        class="accordion-button collapsed collapse-text"
        type="button"
        data-mdb-toggle="collapse"
        data-mdb-target="#collapseThree"
        aria-expanded="false"
        aria-controls="collapseThree"
      >
        Nutritional Information
      </button>
    </h2>
    <div
      id="collapseThree"
      class="accordion-collapse collapse"
      aria-labelledby="headingThree"
      data-mdb-parent="#accordionExample"
    >
      <div class="accordion-body">
        Estimated Serving Size: {{recipe.servingsize}}
        <br>
        Total Calories: {{recipe.calories}}
      </div>
    </div>
  </div>
  </div>
  <div class="card-action changes-box">
    <h3 class="change-box-tit">Change Recipe</h3>
    <a class="edit-link" href="{% url 'recipes_update' recipe.id %}">✎ Edit</a>
    <br>
    <a class="delete-link" href="{% url 'recipes_delete' recipe.id %}"> ✘ Delete</a>
{% for photo in recipe.photo_set.all %} 
  {% comment %} <div class="alert alert-success" style="width: 150px; text-align: center" role="alert">
    Photo was <strong class="success-strong" style="color: rgb(74, 116, 74);">successfully</strong> uploaded!
  </div> {% endcomment %}
{% empty %} 
  {% comment %} <div class="alert alert-danger" style="width: 150px; text-align: center" role="alert">
    Photo was <strong class="success-strong" style="color: #c13a28;">successfully</strong> uploaded!
  </div> {% endcomment %}
{% endfor %} 
  {% comment %} <div class="card-action changes-box"> {% endcomment %}
    <form action="{% url 'add_photo' recipe.id %}" enctype="multipart/form-data" method="POST">
    {% csrf_token %} 
      <div class="custom-file">
       <label class="form-label" style="margin-top: 30px;" for="customFile">Upload Recipe Photo</label>
       <input type="file" style="width: 255px; display: margin-top: 20px; inline-block;" class="form-control upload-input" id="customFile" name="photo-file"/>
      <input type="submit" class="btn btn-secondary photo-btn" value="Upload Photo">
      </div>
    <br><br>
  </form>
  </div>
{% comment %} </div> {% endcomment %}
  </div>
</div>
<hr>
<div class="row">
  <div class="col s6">
        <h3 class="details-sub">Shopping List</h3>
        <p class="details-body">The recipe calls for...</p>
    {% if recipe.ingredients.count %}
      {% for ingredient in recipe.ingredients.all %}
        <div class="card" style="width: 15rem; margin: 0 auto; display: inline-block;">
          <div class="card-content">
            <ul class="list-group list-group-flush">
              <li class="list-group-item ingred-list"> <strong class="ingredient-att">{{ ingredient.amount }}{{ingredient.measurement}}
               </strong> of {{ingredient.ingred_name}}</li>
            </ul>
          </div>
    </div> 

      {% endfor %}
    {% else %}
      <h5>No ingredients have been added.</h5>
    {% endif %}
    <h3 class="details-sub">Recently Used</h3>
    <div class="row">
    <div class="col s6">
      {% if ingredients.count %}
      {% for ingredient in ingredients.all %}
      <form action="{% url 'assoc_ingredient' recipe.id ingredient.id %}" method="post">
           {% csrf_token %}
          {% comment %} <div class="recent-cards" style="max-width: 8rem; text-align:center; display:grid;"> {% endcomment %}
          <div>
            <li class="card-header col-ingred" style="color: #753E5E; margin-right: 50px; max-width: 18rem;">{{ ingredient.ingred_name }}
            <button  type="submit" style="border: 2px solid #5D2B4B; color:#373737;" class="card-titlechip-btn btn-outline-secondary ingredbtn">Add + </button></li>
          </div>
      </form>
      </div>
  </div>
    {% endfor %}
    {% else %}
      <p class="details-body">No recent ingredients available. Please add more ingredients!</p>
    {% endif %}
  </div>  
  <hr>
  <h3 class="details-sub">How did the recipe turn out?</h3>
    <table class="table">
      <thead class="table-dark" style="background: rgb(93, 43, 75);">
        <tr><th>Date</th><th>Name</th><th>Review Info</th><th>Rating No.</th></tr>
      </thead>
      <tbody>
        {% for recipelog in recipe.recipelog_set.all %}
          <tr>
            <td>{{recipelog.date}}</td>
            <td>{{recipelog.review_name}}</td>
            <td>{{recipelog.review}}</td>
            <td>{{recipelog.get_rating_display}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  <div class="col s6">
  <h3 class="details-sub">Create a New Review</h3>
  <form action="{% url 'add_recipelog' recipe.id %}" method="post">
    {% csrf_token %}
    <div class="input-group mb-3 review-form">
      <span class="input-group-text material-icons review-name-icon" id="basic-addon1">people</span>
      <input type="text" style="width: 120px;" name="review_name" class="review-name-input" placeholder="Enter Name" aria-label="Enter Name"
      aria-describedby="basic-addon1" {{recipelog_form.review_name}}
    
      <span class="input-group-text material-icons review-name-icon" id="basic-addon1">people</span>
      <input type="date" class="date-input" placeholder="Select Date" aria-label="Select Date"
      aria-describedby="basic-addon1" style="color: #753E5E; border: 2px initial rgb(50, 48, 50)" {{recipelog_form.date}}
    </div>
    <div class="input-group mb-3 review-form">
      <span class="input-group-text material-icons directions-icon">format_list_numbered</span>
      <textarea class=" review-input" name="review"  aria-label="Review the Recipe"
       placeholder="The recipe review goes right here. Remember, practice makes perfect! Provide feedback for yourself." {{recipelogform.review}}></textarea>
    
      <select type="text" class="rating-select" {{recipelog_form.rating}}
    </div>
    <div class="form-check checkbox review-form">
    <input
      class="form-check-input checkbox"
      type="checkbox"
      value=""
      id="flexCheckDefault"
        {{recipelog_form.recipe_use}}
      <label class="form-check-label" for="flexCheckDefault">
          I have made this recipe.
      </label> 
    <button type="submit" class="btn btn-outline-secondary review-btn" value="Submit Review">Submit</button>
    </div>   
  </div>
  </form>
  </div>
</div>
<script>
  {% comment %} const dateEl = document.getElementById('id_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  }); {% endcomment %}
  $('.datetimepicker').datetimepicker({
    icons: {
        time: "fa fa-clock-o",
        date: "fa fa-calendar",
        up: "fa fa-chevron-up",
        down: "fa fa-chevron-down",
        previous: 'fa fa-chevron-left',
        next: 'fa fa-chevron-right',
        today: 'fa fa-screenshot',
        clear: 'fa fa-trash',
        close: 'fa fa-remove'
    }
}); 
</script>
{% endblock %}

main_app/templates/recipes/index.html
{% extends 'base.html' %} 

{% block content %} 

<h1 class="index-title">What's for <strong class="index-str">Dinner</strong> tonight?</h1>
<p class="index-textBlurb">Check out your recently added recipes! Don't forget to add more recipes to your collection as you further develop your culinary skills.</p>
{% for recipe in recipes %} 

    <div class="card index-card" style="width: 17rem;">
        {% for photo in recipe.photo_set.all %} 
            <img src="{{ photo.url }}" class="card-img-top">
        {% empty %} 
        <img
        src="https://imgur.com/ephVgQ7.jpeg"
        class="card-img-top"
        alt="..."
    />
        {% endfor %} 

        <div class="card-body">
            <h2 class="card-title index-card-title animate__animated animate__zoomInDown">❝ {{ recipe.name }} ❞</h2>
        </div>
        <ul class="list-group list-group-flush index-card-li">
            <li class="list-group-item">Filed Under • {{ recipe.cuisine }} Cuisine</li>
            <li class="list-group-item">The Chef • {{ recipe.author }}</li>
        </ul>
        <div class="card-body">
            <a href="{% url 'detail' recipe.id %}" class="btn btn-outline-info index-card-link">See recipe</a>
        </div>
    </div>
{% endfor %} 

{% endblock %} 

reciperotator/main_app/templates/main_app/photo_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Photo</h1>

  <h4>Are you sure you want to delete {{object.url}}?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'photos_delete' recipe.id %}">Cancel</a>
  </form>
{% endblock %}